# Generated by Django 6.0.7 on 2026-08-19 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60)),
                ('channel_type', models.CharField(choices=[('ecommerce', 'E-commerce'), ('marketplace', 'Marketplace'), ('pos', 'PDV'), ('api', 'API')], default='ecommerce', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_secret', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60)),
                ('marketplace_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente')], default='active', max_length=20)),
                ('commission_type', models.CharField(choices=[('percentage', 'Porcentagem'), ('fixed', 'Fixo')], default='percentage', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplaces', to='ecommerce.channel')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_channel_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='marketplace',
            constraint=models.UniqueConstraint(fields=('tenant', 'channel', 'slug'), name='uniq_marketplace_tenant_channel_slug'),
        ),
    ]
