# Generated by Django 5.1.15 on 2026-08-22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_customuser_shortcuts_db_default'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('plan_code', models.CharField(max_length=40)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_token', models.OneToOneField(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='signup_intent',
                    to='accounts.onetimetoken',
                )),
                ('provisioned_tenant', models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='signup_intent',
                    to='tenancy.tenant',
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='signup_intent',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('status__in', ['pending', 'provisioned'])),
                        name='signup_intent_valid_status',
                    ),
                ],
            },
        ),
    ]
