# Generated by Django 6.0.7 on 2026-07-25 00:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_sprint7_fiscal_models'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(blank=True, choices=[('insumo', 'Insumo'), ('revenda', 'Revenda'), ('servico', 'Servico'), ('brinde', 'Brinde'), ('kit', 'Kit'), ('outro', 'Outro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='scale_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='tracks_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductFiscalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_type', models.CharField(blank=True, choices=[('', 'Nao classificado'), ('revenda', 'Revenda'), ('industrializacao', 'Industrializacao'), ('servico', 'Servico'), ('uso_consumo', 'Uso e Consumo'), ('outro', 'Outro')], default='', max_length=30)),
                ('ncm', models.CharField(blank=True, default='', max_length=8)),
                ('cest', models.CharField(blank=True, default='', max_length=10)),
                ('origin_code', models.CharField(blank=True, default='', max_length=1)),
                ('fiscal_class', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_data', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers', to='catalog.productprice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['product', 'min_quantity'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_quantity__gt', 0)), name='productpricetier_min_quantity_positive'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='productpricetier_amount_nonneg'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'product', 'min_quantity'), name='uniq_productpricetier_tenant_product_qty_active')],
            },
        ),
    ]
