# Generated by Django 6.0.7 on 2026-08-01 02:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sprint24_brand_product_image'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_kits', to='catalog.product')),
                ('kit', models.ForeignKey(help_text='The kit product (product_kind=kit)', on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['kit', 'component'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='productcomposition_quantity_positive'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'kit', 'component'), name='uniq_composition_kit_component_active')],
            },
        ),
    ]
