# Generated by Django 6.0.7 on 2026-08-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_sprint23_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='billing_unit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
