# Generated by Django 6.0.7 on 2026-08-01 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_sprint26_service_fields'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialCombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.commercialcombo')),
            ],
            options={
                'ordering': ['combo', 'item'],
            },
        ),
        migrations.AddConstraint(
            model_name='commercialcombo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'sku'), name='uniq_combo_tenant_sku_active'),
        ),
        migrations.AddConstraint(
            model_name='commercialcombo',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='combo_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='comboitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='comboitem_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='comboitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'combo', 'item'), name='uniq_comboitem_active'),
        ),
    ]
