# Generated by Django 5.2.16 on 2026-08-01 14:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_sprint27_commercial_combos'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('margin_mm', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=8)),
                ('columns', models.PositiveSmallIntegerField(default=2)),
                ('rows', models.PositiveSmallIntegerField(default=5)),
                ('show_sku', models.BooleanField(default=True)),
                ('show_barcode', models.BooleanField(default=True)),
                ('show_price', models.BooleanField(default=True)),
                ('show_name', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('width_mm__gt', 0)), name='label_width_positive'), models.CheckConstraint(condition=models.Q(('height_mm__gt', 0)), name='label_height_positive')],
            },
        ),
    ]
