# Generated by Django 6.0.7 on 2026-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_sprint29_channel_profile'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productchannelprofile',
            name='uniq_channel_profile_prod_slug',
        ),
        migrations.AddConstraint(
            model_name='productchannelprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'channel_slug'), name='uniq_channel_profile_prod_slug'),
        ),
    ]
