# Generated by Django 5.2.16 on 2026-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_sprint30_fix_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='catalog/products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='object_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
