# Generated by Django 5.2.16 on 2026-08-09 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TABLES = [
    'catalog_productapplycommand',
]


def enable_catalog_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            policy = f'{table}_tenant_isolation'
            cursor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(
                f'''
                CREATE POLICY "{policy}" ON "{table}"
                USING (
                    tenant_id::text = current_setting('app.current_tenant_id', true)
                    AND current_setting('app.current_tenant_id', true) <> ''
                )
                WITH CHECK (
                    tenant_id::text = current_setting('app.current_tenant_id', true)
                    AND current_setting('app.current_tenant_id', true) <> ''
                )
                '''
            )


def disable_catalog_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(RLS_TABLES):
            policy = f'{table}_tenant_isolation'
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(f'ALTER TABLE "{table}" NO FORCE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productimage_file_alter_productimage_object_key'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplyCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_id', models.CharField(max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField()),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'command_id'), name='uniq_product_apply_command_tenant_id')],
            },
        ),
        migrations.RunPython(enable_catalog_rls, disable_catalog_rls),
    ]
