# Generated by Django 5.2.16 on 2026-08-09 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productimage_file_alter_productimage_object_key'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplyCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_id', models.CharField(max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField()),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'command_id'), name='uniq_product_apply_command_tenant_id')],
            },
        ),
    ]
