# Generated by Django 5.2.16 on 2026-08-14 04:44

from django.db import migrations, models
from django.db.models import Count


def disambiguate_legacy_idempotency_keys(apps, schema_editor):
    for model_name in ('PurchaseOrder', 'PurchaseReceipt'):
        model = apps.get_model('purchasing', model_name)
        duplicates = (
            model.objects.exclude(idempotency_key='')
            .values('tenant_id', 'idempotency_key')
            .annotate(total=Count('id'))
            .filter(total__gt=1)
        )
        for duplicate in duplicates.iterator():
            rows = model.objects.filter(
                tenant_id=duplicate['tenant_id'],
                idempotency_key=duplicate['idempotency_key'],
            ).order_by('created_at', 'pk')
            for row in rows[1:]:
                row.idempotency_key = f'legacy:{row.pk}'
                row.save(update_fields=['idempotency_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_supplier_person'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.RunPython(
            disambiguate_legacy_idempotency_keys,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_purchase_order_idempotency_tenant'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_purchase_receipt_idempotency_tenant'),
        ),
    ]
