# Generated by Django 5.2.16 on 2026-08-09 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TABLES = [
    'inventory_productstockcontrolcommand',
    'inventory_productstockpolicy',
]


def enable_inventory_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            policy = f'{table}_tenant_isolation'
            cursor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(
                f'''
                CREATE POLICY "{policy}" ON "{table}"
                USING (
                    tenant_id::text = current_setting('app.current_tenant_id', true)
                    AND current_setting('app.current_tenant_id', true) <> ''
                )
                WITH CHECK (
                    tenant_id::text = current_setting('app.current_tenant_id', true)
                    AND current_setting('app.current_tenant_id', true) <> ''
                )
                '''
            )


def disable_inventory_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(RLS_TABLES):
            policy = f'{table}_tenant_isolation'
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(f'ALTER TABLE "{table}" NO FORCE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productapplycommand'),
        ('inventory', '0005_payload_hash_inventory_rls'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockControlCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_id', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('deactivate', 'Deactivate'), ('reactivate', 'Reactivate')], max_length=20)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField()),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'command_id'), name='uniq_product_stock_control_command_tenant_id')],
            },
        ),
        migrations.CreateModel(
            name='ProductStockPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('maximum_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('reorder_point', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('allow_negative', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.branch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_policies', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'branch', 'location'), name='uniq_product_stock_policy_location')],
            },
        ),
        migrations.RunPython(enable_inventory_rls, disable_inventory_rls),
    ]
