# Generated by Django 6.0.7 on 2026-08-01 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


TABLE = 'inventory_productstockpolicy'
POLICY = f'{TABLE}_tenant_isolation'


def enable_product_stock_policy_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'ALTER TABLE "{TABLE}" ENABLE ROW LEVEL SECURITY')
        cursor.execute(f'ALTER TABLE "{TABLE}" FORCE ROW LEVEL SECURITY')
        cursor.execute(f'DROP POLICY IF EXISTS "{POLICY}" ON "{TABLE}"')
        cursor.execute(
            f'''
            CREATE POLICY "{POLICY}" ON "{TABLE}"
            USING (
                tenant_id::text = current_setting('app.current_tenant_id', true)
                AND current_setting('app.current_tenant_id', true) <> ''
            )
            WITH CHECK (
                tenant_id::text = current_setting('app.current_tenant_id', true)
                AND current_setting('app.current_tenant_id', true) <> ''
            )
            '''
        )


def disable_product_stock_policy_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'DROP POLICY IF EXISTS "{POLICY}" ON "{TABLE}"')
        cursor.execute(f'ALTER TABLE "{TABLE}" NO FORCE ROW LEVEL SECURITY')
        cursor.execute(f'ALTER TABLE "{TABLE}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productimage_file_alter_productimage_object_key'),
        ('inventory', '0005_payload_hash_inventory_rls'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('maximum_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('reorder_point', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('allow_negative', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.branch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_policies', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'branch', 'location'), name='uniq_product_stock_policy_location')],
            },
        ),
        migrations.RunPython(
            enable_product_stock_policy_rls,
            disable_product_stock_policy_rls,
        ),
    ]
