# Generated by Django 6.0.7 on 2026-08-05 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_backfill_product_stock_policy'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockControlCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_id', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('deactivate', 'Deactivate'), ('reactivate', 'Reactivate')], max_length=20)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField()),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'command_id'), name='uniq_product_stock_control_command_tenant_id')],
            },
        ),
        migrations.AddIndex(
            model_name='productstockcontrolcommand',
            index=models.Index(fields=['tenant', 'correlation_id'], name='idx_pscc_tenant_corr'),
        ),
        migrations.AddIndex(
            model_name='productstockcontrolcommand',
            index=models.Index(fields=['tenant', 'action'], name='idx_pscc_tenant_action'),
        ),
        migrations.AddIndex(
            model_name='productstockcontrolcommand',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_pscc_tenant_created'),
        ),
    ]
