# Generated by Django 6.0.7 on 2026-08-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productstockcontrolcommand'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productstockcontrolcommand',
            name='idx_pscc_tenant_corr',
        ),
        migrations.RemoveIndex(
            model_name='productstockcontrolcommand',
            name='idx_pscc_tenant_action',
        ),
        migrations.RemoveIndex(
            model_name='productstockcontrolcommand',
            name='idx_pscc_tenant_created',
        ),
    ]
