# Generated by Django 6.0.7 on 2026-08-18 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_brand_ref'),
        ('inventory', '0009_remove_productstockcontrolcommand_idx_pscc_tenant_corr_and_more'),
        ('tenancy', '0007_sprint7_fiscal_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=40)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmada'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='catalog.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_items', to='inventory.stocklocation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.productionorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_items', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_items', to='catalog.unit')),
            ],
            options={
                'ordering': ['order', 'product'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_consumptions', to='catalog.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_consumptions', to='inventory.stocklocation')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_order_consumptions', to='inventory.stocklot')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_consumptions', to='catalog.unit')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.productionorderitem')),
            ],
            options={
                'ordering': ['order_item', 'component'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_production_order_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='productionorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='productionorderitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionorderconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='productionorderconsumption_quantity_positive'),
        ),
    ]
