# Generated by Django 5.2.16 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerefund',
            name='reason',
            field=models.TextField(default='Legacy refund'),
            preserve_default=False,
        ),
    ]
