# Generated by Django 5.2.16 on 2026-08-21 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_merge_f3_quote_salesorder'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('converted', 'Convertido'), ('expired', 'Expirado')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('processing', 'Em processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
    ]
