# Generated by Django 5.2.16 on 2026-07-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_sprint15_saas_commercial_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformadminaudit',
            name='action',
            field=models.CharField(choices=[('plan.created', 'Plano criado'), ('plan.updated', 'Plano atualizado'), ('plan.deleted', 'Plano removido'), ('subscription.created', 'Assinatura criada'), ('subscription.updated', 'Assinatura alterada'), ('subscription.deleted', 'Assinatura removida'), ('subscription.suspended', 'Assinatura suspensa'), ('subscription.activated', 'Assinatura ativada'), ('subscription.cancelled', 'Assinatura cancelada'), ('entitlement.updated', 'Entitlement atualizado'), ('entitlement.deleted', 'Entitlement removido'), ('feature_flag.updated', 'Feature flag alterada'), ('feature_flag.deleted', 'Feature flag removida'), ('support_access.granted', 'Acesso suporte concedido'), ('support_access.revoked', 'Acesso suporte revogado'), ('support_access.deleted', 'Solicitação de suporte removida')], max_length=50),
        ),
    ]
