# Generated by Django 5.2.16 on 2026-08-14 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_payable_status'),
        ('purchasing', '0005_supplier_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='payable',
            name='purchase_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable', to='purchasing.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='payable',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='purchasing.supplier'),
        ),
    ]
