# Generated by Django 6.0.7 on 2026-08-19 01:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_payable_purchase_order_payable_purchase_receipt_and_more'),
        ('tenancy', '0007_sprint7_fiscal_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('system_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('matched', 'Conciliado'), ('partial', 'Parcial'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliations', to='financial.financialaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('effective_date', models.DateField()),
                ('is_matched', models.BooleanField(default=False)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('cashflow_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='financial.cashflowentry')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financial.bankreconciliation')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['effective_date', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_bank_reconciliation_idempotency_tenant'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliationitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lt', 0), _connector='OR'), name='bankreconciliationitem_amount_non_zero'),
        ),
    ]
