# Generated by Django 6.0.7 on 2026-08-19 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_payable_purchase_order_payable_purchase_receipt_and_more'),
        ('fiscal', '0004_repair_fiscal_emitter_active'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalCompensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.CharField(max_length=40)),
                ('compensation_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito'), ('both', 'Ambos')], default='both', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('processed', 'Processado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('compensated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_compensations', to='tenancy.branch')),
                ('fiscal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='fiscal.fiscaldocument')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_fiscal_compensation_tenant_code'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_fiscal_compensation_idempotency_tenant')],
            },
        ),
    ]
