# Generated by Django 5.2.16 on 2026-08-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_billing'),
        ('financial', '0005_fiscalcompensation'),
    ]

    operations = [
    ]
